server:
  port: 8686
  servlet:
    context-path: /ql/chat

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ql_chat?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: password
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: host
    port: 6379
    password: password
  profiles:
    active: dev

mybatis-plus:
  global-config:
    db-config:
      id-type: auto

sa-token:
  token-name: Authorization
  token-style: random-128
  is-read-cookie: true
  is-read-body: false
  is-concurrent: true
  is-read-header: false
  is-share: true
  is-log: true
  timeout: -1
  active-timeout: -1